Website/RMSS Website/Models/Persons/PersonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMSS_Website.Models.Persons {
    public class PersonModel {
        public PersonModel() {
            PersonViewModel = new PersonViewModel();
        }
        public string PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string OfficeNumber { get; set; }
        public string MobileNumber { get; set; }
        public PersonViewModel PersonViewModel { get; set; }
    }

    public class PersonViewModel {
        public string SelectedPersonID { get; set; }
        public List<SelectListItem> AvailablePersons { get; set; }
    }
}

Website/RMSS Website/Controllers/PersonController.cs
using RMSS_Website.Factories;
using RMSS_Website.Objects;
using RMSS_Website.Objects.Web_Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMSS_Website.Controllers
{
    public class PersonController : Controller
    {
        // GET: Person
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ModifyPersons(string PersonID) {
            MvcApplication.CheckEmployeeLogin();
            if (!UserFactory.HasPermission(SessionData.UserID, Permissions.ModifyPersons))
                return RedirectToAction("Unauthorized", "Home");
            var model = PersonFactory.GetPersonModel(PersonID);
            return View(model);
        }

        public ActionResult UpdatePersonTextbox(string Type, string Value, string PersonID) {
            var dataContext = MvcApplication.GetDataContext();
            var person = dataContext.Persons.FirstOrDefault(p => p.PersonID == PersonID);
            if (person == null)
                return new JsonNetResult("Person does not exist? Try refreshing the page.", 500);
            switch(Type) {
                case PersonField.FirstName:
                    person.FirstName = Value;
                    MvcApplication.AddTransactionLog(string.Format("User set first name of {0} to {1}", person.FirstName + " " + person.LastName, Value));
                    break;
                case PersonField.LastName:
                    person.LastName = Value;
                    MvcApplication.AddTransactionLog(string.Format("User set last name of {0} to {1}", person.FirstName + " " + person.LastName, Value));
                    break;
                case PersonField.Email:
                    person.Email = Value;
                    MvcApplication.AddTransactionLog(string.Format("User set email of {0} to {1}", person.FirstName + " " + person.LastName, Value));
                    break;
                case PersonField.OfficeNumber:
                    person.OfficeNumber = Value;
                    MvcApplication.AddTransactionLog(string.Format("User set office number of {0} to {1}", person.FirstName + " " + person.LastName, Value));
                    break;
                case PersonField.MobileNumber:
                    person.MobileNumber = Value;
                    MvcApplication.AddTransactionLog(string.Format("User set mobile number of {0} to {1}", person.FirstName + " " + person.LastName, Value));
                    break;
            }
            dataContext.SubmitChanges();
            return new JsonNetResult("Person successfully updated.");
        }

        public ActionResult AddPerson(string FirstName, string LastName, string Email, string OfficeNumber, string MobileNumber) {
            var dataContext = MvcApplication.GetDataContext();
            var person = dataContext.Persons.FirstOrDefault(u => u.FirstName == FirstName && u.LastName == LastName && u.Email == Email);
            if (person != null) {
                ViewData["Error"] = "Persons must have unique first names, last names or emails.";
                return View("~/Views/Person/ModifyPersons.cshtml", PersonFactory.GetPersonModel(null));
            }
            if (string.IsNullOrEmpty(FirstName) || string.IsNullOrEmpty(LastName)) {
                ViewData["Error"] = "Person's first and last names cannot be empty.";
                return View("~/Views/Person/ModifyPersons.cshtml", PersonFactory.GetPersonModel(null));
            }
            var id = Guid.NewGuid().ToString();
            dataContext.Persons.InsertOnSubmit(new Person {
                PersonID = id,
                FirstName = FirstName,
                LastName = LastName,
                Email = Email,
                OfficeNumber = OfficeNumber,
                MobileNumber = MobileNumber
            });
            dataContext.SubmitChanges();
            MvcApplication.AddTransactionLog(string.Format("User added person {0}", FirstName + " " + LastName));
            return RedirectToAction("ModifyPersons", new { PersonID = id });
        }
    }
}

Website/RMSS Website/Views/Person/ModifyPersons.cshtml
@using RMSS_Website.Objects.Web_Objects.CustomControl

@{
    ViewBag.Title = "Modify Person";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model RMSS_Website.Models.Persons.PersonModel

@section content_Content {
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div id="existingPersons">
        <span id="spanPersonID" style="display:none;">@Model.PersonID</span>
        @SectionHeading.RenderMVC("Edit Existing Person")
        <label>Select Person: </label> @(Html.Kendo().ComboBox().Name("SelectPerson").Placeholder("--- Select ---").BindTo(Model.PersonViewModel.AvailablePersons).Filter("contains").Events(
            e => e.Change("PersonChanged")).Value(Model.PersonViewModel.SelectedPersonID).AutoWidth(true).HtmlAttributes(new { style = "width: 50%;" }))
        <table style="padding:10px; width:50%;">
            <tr><td><label>First Name: </label></td><td><input type="text" value="@Model.FirstName" onchange="UpdatePersonTextbox('FirstName', this);" /></td>
            <tr />
            <tr><td><label>Last Name: </label></td><td><input type="text" value="@Model.LastName" onchange="UpdatePersonTextbox('LastName', this);" /></td></tr>
            <tr><td><label>Email: </label></td><td><input type="text" value="@Model.Email" onchange="UpdatePersonTextbox('Email', this);" /></td></tr>
            <tr><td><label>Office Number: </label></td><td><input type="text" value="@Model.OfficeNumber" onchange="UpdatePersonTextbox('OfficeNumber', this);" /></td>
            <tr />
            <tr><td><label>Mobile Number: </label></td><td><input type="text" value="@Model.MobileNumber" onchange="UpdatePersonTextbox('MobileNumber', this);" /></td></tr>
        </table>
    </div>
    <div id="newPersons">
        @SectionHeading.RenderMVC("Add New Person")
        <label style="color:red;">@ViewData["Error"]</label>
        <form action="@Url.Action("AddPerson", "Person")">
            <table style="padding:10px; width:50%;">
                <tr><td><label>First Name: </label></td><td><input type="text" name="FirstName" /></td> <tr />
                <tr><td><label>Last Name: </label></td><td><input type="text" name="LastName" /></td></tr>
                <tr><td><label>Email: </label></td><td><input type="text" name="Email" /></td></tr>
                <tr><td><label>Office Number: </label></td><td><input type="text" name="OfficeNumber"/></td> <tr />
                <tr><td><label>Mobile Number: </label></td><td><input type="text" name="MobileNumber" /></td></tr>
                <tr><td><input type="submit" value="Add" /></td></tr>
            </table>
        </form>
    </div>
    <script>
        function UpdatePersonTextbox(Type, Textbox) {
            $.ajax({
                type: 'POST',
                url: "@Url.Action("UpdatePersonTextbox", "Person")",
                data: { Type: Type, Value: Textbox.value , PersonID: $('#spanPersonID').text() },
                error: function (xhr, status, errorThrown) {
                    ToastrPopup(xhr.responseText, 'error');
                }
            });
        }
        function PersonChanged() {
            var link = "@Url.Action("ModifyPersons", "Person", new { PersonID = "x01"})";
            link = link.replace("x01", $('#SelectPerson').data("kendoComboBox").value());
            window.location = link;
        }
        
    </script>
    <style>
        td {
            padding:3px;
            width:50%;
        }
    </style>
</body>
</html>
}