Website/RMSS Website/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMSS_Website.Models.Persons;
using RMSS_Website.Objects;
using RMSS_Website.Factories;
using RMSS_Website.Objects.Web_Objects;

namespace RMSS_Website.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AuthApi(string FirstName, string LastName, string Email)
        {
            var dataContext = MvcApplication.GetDataContext();
            var person = dataContext.Persons.FirstOrDefault(u => u.FirstName == FirstName && u.LastName == LastName && u.Email == Email);
            if (person != null)
            {
                ViewData["Error"] = "Persons must have unique first names, last names or emails.";
                //return View("~/Views/User/SignUp.cshtml", PersonFactory.GetPersonModel(null));
                return Json(new { success = "exists", message = "Persons must have unique first names, last names or emails." }, JsonRequestBehavior.AllowGet);
            }
            if (string.IsNullOrEmpty(FirstName) || string.IsNullOrEmpty(LastName) || string.IsNullOrEmpty(Email))
            {
                ViewData["Error"] = "Person's first and last names cannot be empty.";
                return Json(new { success = "empty", message = "Person's first and last names cannot be empty." }, JsonRequestBehavior.AllowGet);
            }
            var id = Guid.NewGuid().ToString();
            dataContext.Persons.InsertOnSubmit(new Person
            {
                PersonID = id,
                FirstName = FirstName,
                LastName = LastName,
                Email = Email
              
            });
            dataContext.SubmitChanges();
            MvcApplication.AddTransactionLog(string.Format("Visitor added as a person {0}", FirstName + " " + LastName));
            return Json(new { success = "done", id = id }, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult AddVisitor(string FirstName, string LastName, string Email, string OfficeNumber, string MobileNumber)
        {
            var dataContext = MvcApplication.GetDataContext();
            var person = dataContext.Persons.FirstOrDefault(u => u.FirstName == FirstName && u.LastName == LastName && u.Email == Email);
            if (person != null)
            {
                ViewData["Error"] = "Persons must have unique first names, last names or emails.";
                return View("~/Views/Person/ModifyPersons.cshtml", PersonFactory.GetPersonModel(null));
            }
            if (string.IsNullOrEmpty(FirstName) || string.IsNullOrEmpty(LastName))
            {
                ViewData["Error"] = "Person's first and last names cannot be empty.";
                return View("~/Views/Person/ModifyPersons.cshtml", PersonFactory.GetPersonModel(null));
            }
            var id = Guid.NewGuid().ToString();
            dataContext.Persons.InsertOnSubmit(new Person
            {
                PersonID = id,
                FirstName = FirstName,
                LastName = LastName,
                Email = Email,
                OfficeNumber = OfficeNumber,
                MobileNumber = MobileNumber
            });
            dataContext.SubmitChanges();
            MvcApplication.AddTransactionLog(string.Format("Visitor added as a person {0}", FirstName + " " + LastName));
            return RedirectToAction("SignUpVisitor", new { PersonID = id });
        }
        public ActionResult SignUpVisitor(string PersonID)
        {
            var model = PersonFactory.GetPersonModel(PersonID);
            return View(model);
        }
        public ActionResult AddSignUpVisitor(string SelectedPersonID, string Username, string Password)
        {
            if (string.IsNullOrEmpty(Username) || string.IsNullOrEmpty(Password))
            {
                ViewData["Error"] = "You must enter a username and a password";
                return Json(new { success = "empty", message = "You must enter a username and a password" }, JsonRequestBehavior.AllowGet);
            }
            if (string.IsNullOrEmpty(SelectedPersonID))
            {
                ViewData["Error"] = "The user does not exists";
                return Json(new { success = "exists", message = "The user does not exists" }, JsonRequestBehavior.AllowGet);
            }
            var dataContext = MvcApplication.GetDataContext();
            var person = dataContext.Persons.FirstOrDefault(p => p.PersonID == SelectedPersonID);
            if (person == null)
                return Json(new { success = "exists", message = "The user does not exists" }, JsonRequestBehavior.AllowGet);
            var existingUser = dataContext.Users.FirstOrDefault(p => p.PersonID == SelectedPersonID || p.Username == Username);
            if (existingUser != null)
                return Json(new { success = "existsa", message = "The user already exists" }, JsonRequestBehavior.AllowGet);
            var newID = Guid.NewGuid().ToString();
            var SA = MvcApplication.GetSaltCharacters();
            var pass = MvcApplication.GetEncryptedPassword(Password + SA.Item1 + SA.Item2);
            dataContext.Users.InsertOnSubmit(new User
            {
                UserID = newID,
                Username = Username,
                Password = pass,
                SA = string.Format("{0}{1}", SA.Item1, SA.Item2),
                IsAdmin = false,
                IsEmployee = false,
                PersonID = SelectedPersonID
            });
            MvcApplication.AddTransactionLog(string.Format("Visitor {0} added for person {1} {2}", Username, person.FirstName, person.LastName));
            dataContext.SubmitChanges();
            //return RedirectToAction("Index", "Home");
            return Json(new { success = "done", message = "done" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult TryAgainRequest(string ID)
        {
            var dataContext = MvcApplication.GetDataContext();
            var user = dataContext.Persons.FirstOrDefault(c => c.PersonID == ID);
            if(user != null)
            {
                dataContext.Persons.DeleteOnSubmit(user);
                dataContext.SubmitChanges();
                return Json(new { success = "done", message = "deleted details of user" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = "notexists", message = "Person doesnt exists" }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

Website/RMSS Website/Views/SignUp/SignUpVisitor.cshtml
@using RMSS_Website.Objects.Web_Objects.CustomControl

@{
    ViewBag.Title = "The Risk Manager - Sign Up Visitor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model RMSS_Website.Models.Persons.PersonModel

@section content_Content {
    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title></title>
    </head>
    <body>



        <h3> Welcome @Model.FirstName, Please complete the form below to get started</h3>
        <div class="alert alert-danger" id="error" style="display:none;">
            Cannot register the user at this time, please try again later
        </div>
        <div class="alert alert-danger" id="empty" style="display:none;">
            You must enter a username and a password
        </div>
        <div class="alert alert-danger" id="exists" style="display:none;">
            The user does not exists
        </div>
        <div class="alert alert-danger" id="existsa" style="display:none;">
            The user already exists
        </div>
        <div class="alert alert-success" id="success" style="display:none;">
            Congratulations, you have been registered with TheRiskManager
        </div>
        <div class="alert alert-danger" id="not" style="display:none;">
            Your details cannot be modified at this time
        </div>
        <div class="alert alert-warning" id="again" style="display:none;">
            Your details are deleted, please try again with your new details
        </div>
        <table style="padding:10px; width:50%;">
            <tr>
                <td><label>First Name: </label></td>
                <td>
                    @*<input type="text" value="@Model.FirstName" />*@
                    <p>@Model.FirstName</p>
                </td>
            <tr />
            <tr>
                <td><label>Last Name: </label></td>
                <td>
                    @*<input type="text" value="@Model.LastName"  />*@
                    <p>@Model.LastName</p>
                </td>
            </tr>
            <tr>
                <td><label>Email: </label></td>
                <td>
                    @*<input type="text" value="@Model.Email" />*@
                    <p>@Model.Email</p>
                </td>
            </tr>
            <tr>
                <td><label>Office Number: </label></td>
                <td>
                    @*<input type="text" value="@Model.OfficeNumber" />*@
                    <p>@Model.OfficeNumber</p>
                </td>
            <tr />
            <tr>
                <td><label>Mobile Number: </label></td>
                <td>
                    @*<input type="text" value="@Model.MobileNumber" />*@
                    <p>@Model.MobileNumber</p>
                </td>
            </tr>
        </table>

        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12" style="text-align:right;">
                    <p>Are the provided details not correct?</p>
                    <button class="btn btn-primary" id="tryagain">Try Again?</button>
                </div>
            </div>
        </div>

        <section id="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div id="vd">


                            <input id="spanPersonID" style="display:none;" value="@Model.PersonID" />

                            @*<form action="@Url.Action("AddVisitor", "SignUp")">*@
                            @*<label style="color:red;">@ViewData["Error"]</label>*@
                            <div class="row">
                                <div class="col-md-4 col-sm-12">
                                    <p>Choose a username</p>

                                </div>
                                <div class="col-md-8 col-sm-12">
                                    <label><input type="text" required id="UserName" /></label>
                                </div>
                                <div class="col-md-4 col-sm-12">
                                    <p>Choose a password</p>

                                </div>
                                <div class="col-md-8 col-sm-12">
                                    <label><input type="password" required id="Password"></label>
                                </div>
                                <div class="col-md-8 col-sm-12">
                                    <button class="btn btn-primary" id="sign-up">Sign Up</button>
                                </div>
                            </div>

                            @*</form>*@




                        </div>


                    </div>


                </div>

            </div>
        </section>


        <script>



        $("#sign-up").on("click", function () {

                $.ajax({
                    type: 'POST',
                    url: "@Url.Action("AddSignUpVisitor", "SignUp")",
                    data: { SelectedPersonID: $("#spanPersonID").val(), UserName: $("#UserName").val(), Password: $("#Password").val() },
                    success: function (data) {
                        if (data.success == "empty") {
                            $("#empty").show();
                            setTimeout(
                                function () {
                                    $("#empty").hide();
                                }, 900);
                        }
                        if (data.success == "exists") {
                            $("#exists").show();
                            setTimeout(
                                function () {
                                    $("#exists").hide();
                                }, 900);
                        }
                        if (data.success == "existsa") {
                            $("#existsa").show();
                            setTimeout(
                                function () {
                                    $("#existsa").hide();
                                }, 900);
                        }

                        else if (data.success == "done") {
                            //ToastrPopup('You have been successfully registered');
                           $.ajax({
                                type: 'Post',
                                url: "@Url.Action("ProcessLogin", "User")",
                                data: { Username: $('#UserName').val(), Password: $('#Password').val() },
                               success: function (data, status, xhr) {
                                   $("#success").show();
                                   setTimeout(
                                       function () {
                                           window.location.href = data;
                                       }, 900);
                                },
                                error: function (xhr, status, errorThrown) {
                                    //$("#loginalert").show();
                                    ToastrPopup(xhr.responseText, 'error');
                                    console.log("xhr: " + xhr.responseText + " status: " + status + " errorThrown: " + errorThrown);
                                }
                                });
                           // window.location.replace("@Url.Action("Index","Home")");

                                        }
                    },
                    error: function (xhr, status, errorThrown) {
                        //ToastrPopup(xhr.responseText, 'error');
                        $("#error").show();
                    }
                });

        });
             $("#tryagain").on("click",function(e) {
                 $.ajax({
                     url: '@Url.Action("TryAgainRequest", "SignUp")',
                     type: "POST",
                     data: {
                         ID: $("#spanPersonID").val()
                     },
                     success: function (data, status, xhr) {
                         if (data.success == "done") {
                             $("#again").show();
                             console.log(data.message);
                             setTimeout(
                                 function () {
                                     window.location.replace("/User/SignUp");
                                 }, 1000);
                         }
                         else if (data.success == "notexists") {
                             $("#not").show();
                             console.log(data.message);
                             setTimeout(
                                 function () {
                                     window.location.reload();
                                 }, 900);
                         }
                     },
                     error: function (xhr, status, errorThrown) {
                         //ToastrPopup(xhr.responseText, 'error');
                         $("#not").show();
                         setTimeout(
                             function () {
                                 window.location.reload();
                             }, 900);

                     }
                 });
    });

        </script>
        <style>
            td {
                padding: 3px;
                width: 50%;
            }
        </style>
    </body>
</html>
}