Website/RMSS Website/Models/Clients/ClientModel.cs
using RMSS_Website.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMSS_Website.Models.Clients {

    public class ClientSelect {
        public ClientSelect() {
            clients = new List<ClientModelShort>();
        }
        public List<ClientModelShort> clients { get; set; }
        public bool canModify { get; set; }
    }
    public class ClientModelShort {
        public string ClientID { get; set; }
        public string ClientName { get; set; }
        public string Status { get; set; }
    }

    public class ClientModelGrid {
        public string ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientStatus { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string Modules { get; set; }
        public int? UserLimit { get; set; }
        public int? Version { get; set; }
        public int? SubVersion { get; set; }
    }

    public class ClientModel {
        public ClientModel() {
            Notes = new List<ClientNote>();
            Contacts = new List<ClientContact>();
        }
        public string ClientID { get; set; }
        public string ClientName { get; set; }
        //public string Status { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public int UserLimit { get; set; }
        public string ProductionURL { get; set; }
        public string TrainingURL { get; set; }
        public string ThirdURL { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreatorPerson { get; set; }
        public int VersionNumber { get; set; }
        public int VersionSubNumber { get; set; }
        public List<ClientNote> Notes { get; set; }
        public List<ClientContact> Contacts { get; set; }
        public StatusViewModel Status { get; set; }
        public ModuleViewModel Modules { get; set; }
        public ClientLinkedEmployeesModel LinkedEmployees { get; set; }
        public List<SelectListItem> AvailableContacts { get; set; }
    }

    public class ClientLinkedEmployeesModel {
        public string AccountManagerID { get; set; }
        public string ClientSupportCoordinatorID { get; set; }
        public string AccountManagerName { get; set; }
        public string ClientSupportCoordinatorName { get; set; }
        public IEnumerable<SelectListItem> AvailablePeople { get; set; }
    }

    public class StatusViewModel {
        public string SelectedStatusID { get; set; }
        public IEnumerable<SelectListItem> Status { get; set; }
        public string SelectedStatusName { get; set; }
    }

    public class ModuleViewModel {
        public List<string> SelectedModuleIDs { get; set; }
        public List<ProductModule> ProductModules { get; set; }
        public string SelectedModuleNames { get; set; }
    }

    public class ClientNote {
        public string ClientNoteID { get; set; }
        public string Note { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool? Pinned { get; set; }
        public string Creator { get; set; }
        public string Heading { get; set; }
    }

    public class ClientContact {
        public string ClientID { get; set; }
        public string PersonID { get; set; }
        public string Name { get; set; }
        public string OfficeNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
    }

    public class ClientProductModule {
        public string ClientID { get; set; }
        public string ProductModuleID { get; set; }
        public string Name { get; set; }
    }
}

Website/RMSS Website/Controllers/ClientsController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using RMSS_Website.Factories;
using RMSS_Website.Models.Clients;
using RMSS_Website.Objects;
using RMSS_Website.Objects.Web_Objects;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMSS_Website.Controllers {
    public class ClientsController : Controller {
        // GET: Clients
        public ActionResult Index() {
            return View();
        }

        public ActionResult ClientInfo(string ClientName) {
            MvcApplication.CheckEmployeeLogin();
            var model = ClientFactory.GetClientModel(ClientName);
            if (model != null)
                return View(model);
            else
                throw new Exception("Invalid client Name");
        }

        private ClientModel GetModel(string ClientName) {
            var model = ClientFactory.GetClientModel(ClientName);
            if (model != null) {
                SessionData.CurrentClientID = MvcApplication.GetDataContext().Clients.FirstOrDefault(c => c.ClientName == ClientName).ClientID;
                return model;
            } else
                throw new Exception("Invalid client name");
        }

        public ActionResult ModifyClient(string ClientName) {
            MvcApplication.CheckEmployeeLogin();
            if (!UserFactory.HasPermission(SessionData.UserID, Permissions.ModifyClients))
                return RedirectToAction("Unauthorized", "Home");
            return View(GetModel(ClientName));
        }

        public ActionResult SelectClient() {
            MvcApplication.CheckEmployeeLogin();
            var model = new ClientSelect();
            model.clients = ClientFactory.GetShortClientModels();
            model.canModify = UserFactory.HasPermission(SessionData.UserID, Permissions.ModifyClients);
            if (model != null)
                return View(model);
            else
                throw new Exception("Error getting client models.");
        }

        public ActionResult ClientFilter() {
            MvcApplication.CheckEmployeeLogin();
            var model = SessionData.ClientFilter;
            if (model != null)
                return View(model);
            else
                throw new Exception("Error getting client filter model.");
        }

        public ActionResult ClientGrid() {
            MvcApplication.CheckEmployeeLogin();
            var model = ClientFactory.GetClientGridModels();
            if (model != null)
                return View(model);
            else
                throw new Exception("Error getting client grid model.");
        }

        
        public ActionResult GetClientGridData([DataSourceRequest]DataSourceRequest request) {
            return Json(ClientFactory.GetClientGridModels().ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteClient(string clientName) {
            return AlterClients(clientName, "Deleted");
        }

        public ActionResult AddClient(string clientName) {
            return AlterClients(clientName, "Added");
        }

        private ActionResult AlterClients(string clientName, string commandName) {
            var dataContext = MvcApplication.GetDataContext();
            var user = dataContext.Users.FirstOrDefault(u => u.UserID == SessionData.UserID);
            if (user == null || !user.IsEmployee.GetValueOrDefault(false))
                return new JsonNetResult("You are not authorized to do this.", 401);

            if (string.IsNullOrEmpty(clientName))
                return new JsonNetResult("Client name cannot be empty.", 400);

            if (commandName == "Added") {
                var existingClient = dataContext.Clients.FirstOrDefault(c => c.ClientName == clientName);
                if (existingClient != null)
                    return new JsonNetResult("There is already a client with this name.", 400);
                else {
                    dataContext.Clients.InsertOnSubmit(new Client {
                        ClientID = Guid.NewGuid().ToString(),
                        ClientName = clientName,
                        CreatorPersonID = user.PersonID,
                        CreateDate = DateTime.Now
                    });
                    dataContext.SubmitChanges();
                }
                MvcApplication.AddTransactionLog("Added client " + clientName);
            } else if (commandName == "Deleted") {
                var client = dataContext.Clients.FirstOrDefault(c => c.ClientName == clientName);
                if (client == null)
                    return new JsonNetResult("Error finding client to delete.", 400);
                else {
                    try {
                        dataContext.Clients.DeleteOnSubmit(client);
                        dataContext.SubmitChanges();
                        MvcApplication.AddTransactionLog("Deleted client " + clientName);
                    } catch (Exception ex) {
                        return new JsonNetResult("You cannot delete a client already bound to existing data. Set their status to inactive instead.", 400);
                    }
                }
            }
            return new JsonNetResult(ClientFactory.GetShortClientModels());
        }

        public ActionResult UpdateDate(string Date, string ClientID) {
            var dataContext = MvcApplication.GetDataContext();
            var client = dataContext.Clients.FirstOrDefault(c => c.ClientID == ClientID);
            if (client == null)
                return new JsonNetResult("Client does not exist", 400);
            var initialDate = client.ExpiryDate;
            client.ExpiryDate = DateTime.Parse(Date);
            dataContext.SubmitChanges();
            MvcApplication.AddTransactionLog(string.Format("Update expiry date for {0} from {1} to {2}", client.ClientName, initialDate, Date));
            return new JsonNetResult("Successfully update date.");
        }

        public ActionResult UpdateClientInt(string Value, string Type, string ClientID) {
            var dataContext = MvcApplication.GetDataContext();
            var client = dataContext.Clients.FirstOrDefault(c => c.ClientID == ClientID);
            if (client == null)
                return new JsonNetResult("Client does not exist", 400);
            switch(Type) {
                case ClientField.UserLimit:
                    var initialUserLimit = client.UserLimit;
                    client.UserLimit = Int32.Parse(Value);
                    dataContext.SubmitChanges();
                    MvcApplication.AddTransactionLog(string.Format("Updated user limit for {0} from {1} to {2}", client.ClientName, initialUserLimit, Value));
                    break;
                case ClientField.VersionNumber:
                    var initialVersionNumber = client.VersionNumber;
                    client.VersionNumber = Int32.Parse(Value);
                    dataContext.SubmitChanges();
                    MvcApplication.AddTransactionLog(string.Format("Updated version number for {0} from {1} to {2}", client.ClientName, initialVersionNumber, Value));
                    break;
                case ClientField.VersionSubNumber:
                    var initialVersionSubNumber = client.VersionSubNumber;
                    client.VersionSubNumber = Int32.Parse(Value);
                    dataContext.SubmitChanges();
                    MvcApplication.AddTransactionLog(string.Format("Updated version sub number for {0} from {1} to {2}", client.ClientName, initialVersionSubNumber, Value));
                    break;
                default:
                    return new JsonNetResult("Invalid field selected?", 500);
            }
            return new JsonNetResult("Successfully updated " + Type);
        }

        public ActionResult UpdateModule(string ModuleID, string ClientID) {
            var dataContext = MvcApplication.GetDataContext();
            var client = dataContext.Clients.FirstOrDefault(c => c.ClientID == ClientID);
            var module = dataContext.ProductModules.FirstOrDefault(m => m.ProductModuleID == ModuleID);
            if (client == null || module == null)
                return new JsonNetResult("Client or product module was null", 500);
            var clientModule = dataContext.ClientProductModules.FirstOrDefault(c => c.ClientID == ClientID && c.ProductModuleID == ModuleID);
            if (clientModule == null) {
                dataContext.ClientProductModules.InsertOnSubmit(new Objects.ClientProductModule {
                    ProductModuleID = ModuleID,
                    ClientID = ClientID
                });
                MvcApplication.AddTransactionLog(string.Format("Added module {0} to client {1}", module.ModuleName, client.ClientName));
            } else {
                dataContext.ClientProductModules.DeleteOnSubmit(clientModule);
                MvcApplication.AddTransactionLog(string.Format("Removed module {0} from client {1}", module.ModuleName, client.ClientName));
            }
            dataContext.SubmitChanges();
            return new JsonNetResult("Successfully updated module.");
        }

        public ActionResult UploadClientLogo(HttpPostedFileBase file) {
            var dataContext = MvcApplication.GetDataContext();
            var client = dataContext.Clients.FirstOrDefault(c => c.ClientID == SessionData.CurrentClientID);
            var result = FileFactory.UploadFile(dataContext, file, FileReferences.ClientLogo, null, client.ClientLogoID);
            
            if (result.HasErrors) {
                return new JsonNetResult(string.Join(",", result.ErrorMessages), 400);
            }
            if (result.ResponseObject != null) {
                client.ClientLogoID = result.ResponseMessages.FirstOrDefault();
                dataContext.SubmitChanges();

Website/RMSS Website/Views/Clients/ClientFilter.cshtml
@{
    ViewBag.Title = "Client Filter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model RMSS_Website.Objects.Objects.Filters.ClientFilter
@using objects = RMSS_Website.Objects;

@section content_Content {
    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title></title>
    </head>
    <body>
        <div>
            <h2> @(string.IsNullOrEmpty(Model.FoundClientName) ? "Available Clients: " + @Model.NumberOfClients : "Found Client: " + @Model.FoundClientName)</h2>
            <table>
                <tr>
                    <td><label>Client Name: </label></td>
                    <td><input type="text" id="txtClientName" onchange="txtClientNameChange" value="@Model.ClientName" /></td>
                </tr>
                <tr>
                    <td><label>Client Status: </label></td>
                    <td>@Html.DropDownListFor(x => x.StatusView.SelectedStatusID, Model.StatusView.AvailableStatuses, "--- Select ---")</td>
                </tr>
                <tr>
                    <td><label>Expiry Date: </label></td>
                    <td>
                        @(Html.Kendo().DatePicker().Name("ExpiryDateAFterPicker").Value(Model.ExpiryDateAfter).Format("dd/MM/yyyy").Events(e => e.Change("ExpiryDateAfterChanged"))) <span> to </span>
                        @(Html.Kendo().DatePicker().Name("ExpiryDateBeforePicker").Value(Model.ExpiryDateBefore).Format("dd/MM/yyyy").Events(e => e.Change("ExpiryDateBeforeChanged")))
                    </td>
                </tr>
                <tr>
                    <td><label>User Limit: </label></td>
                    <td>
                        @(Html.Kendo().NumericTextBox().Name("UserLimitAbove").Value(Model.UserLimitAbove).Events(e => e.Change("UserLimitAboveChanged")).Decimals(0).Format("#")) <span> to </span>
                        @(Html.Kendo().NumericTextBox().Name("UserLimitBelow").Value(Model.UserLimitBelow).Events(e => e.Change("UserLimitBelowChanged")).Decimals(0).Format("#"))
                    </td>
                </tr>
                <tr>
                    <td><label>Account Manager: </label></td>
                    <td>@Html.DropDownListFor(x => x.ManagerView.SelectedAccountManagerID, Model.ManagerView.AvailableAccountManagers, "--- Select ---")</td>
                </tr>
                <tr>
                    <td><label>Client Support Coordinator: </label></td>
                    <td>@Html.DropDownListFor(x => x.ClientSupportView.SelectedClientSupportCoordinatorID, Model.ClientSupportView.AvailableClientSupportCoordinators, "--- Select ---")</td>
                </tr>
                <tr>
                    <td><label>Creator: </label></td>
                    <td>@Html.DropDownListFor(x => x.CreatorView.SelectedCreatorID, Model.CreatorView.AvailableCreators, "--- Select ---")</td>
                </tr>
                <tr>
                    <td><label>Version Number Above: </label></td>
                    <td>
                        @(Html.Kendo().NumericTextBox().Name("VersionNumberAbove").Value(Model.VersionNumberAbove).Events(e => e.Change("VersionNumberAboveChanged")).Decimals(0).Format("#"))
                        @(Html.Kendo().NumericTextBox().Name("VersionSubNumberAbove").Value(Model.VersionSubNumberAbove).Events(e => e.Change("VersionSubNumberAboveChanged")).Decimals(0).Format("#"))
                    </td>
                </tr>
                <tr>
                    <td><label>Version Number Below: </label></td>
                    <td>
                        @(Html.Kendo().NumericTextBox().Name("VersionNumberBelow").Value(Model.VersionNumberBelow).Events(e => e.Change("VersionNumberBelowChanged")).Decimals(0).Format("#"))
                        @(Html.Kendo().NumericTextBox().Name("VersionSubNumberBelow").Value(Model.VersionSubNumberBelow).Events(e => e.Change("VersionSubNumberBelowChanged")).Decimals(0).Format("#"))
                    </td>
                </tr>
            </table>
            <div style="margin: 0 auto;">
                <button onclick="@("window.location.href='" + Url.Action("ClientGrid", "Clients") + "'");">Open Client Grid</button> 
                <button onclick="ResetFilter(); return false;">Clear Filter</button>
            </div>
            <script>
                function ResetFilter() {
                    $.ajax({
                        type: 'POST',
                        url: "@Url.Action("ResetClientFilter", "Clients")",
                       success: function (data) {
                           window.location.reload(true);
                       },
                       error: function (xhr, status, errorThrown) {
                            ToastrPopup(xhr.responseText, 'error');
                            console.log("xhr: " + xhr.responseText + " status: " + status + " errorThrown: " + errorThrown);
                        }
                    });
                }
                $('#StatusView_SelectedStatusID').change(function () {
                    UpdateDropdownListSelection(this.value, '@objects.ClientFilterField.ClientStatusID');
                });
                $('#ManagerView_SelectedAccountManagerID').change(function () {
                    UpdateDropdownListSelection(this.value, '@objects.ClientFilterField.AccountManagerID');
                });
                $('#ClientSupportView_SelectedClientSupportCoordinatorID').change(function () {
                    UpdateDropdownListSelection(this.value, '@objects.ClientFilterField.ClientSupportID');
                });
                $('#CreatorView_SelectedCreatorID').change(function () {
                    UpdateDropdownListSelection(this.value, '@objects.ClientFilterField.CreatorID');
                });

                function VersionSubNumberBelowChanged() {
                    UpdateInt(this.value(), '@objects.ClientFilterField.VersionSubNumberBelow');
                }
                function VersionNumberBelowChanged() {
                    UpdateInt(this.value(), '@objects.ClientFilterField.VersionNumberBelow');
                }
                function VersionNumberAboveChanged() {
                    UpdateInt(this.value(), '@objects.ClientFilterField.VersionNumberAbove');
                }
                function VersionSubNumberAboveChanged() {
                    UpdateInt(this.value(), '@objects.ClientFilterField.VersionSubNumberAbove');
                }
                function UserLimitAboveChanged() {
                    UpdateInt(this.value(), '@objects.ClientFilterField.UserLimitAbove');
                }
                function UserLimitBelowChanged() {
                    UpdateInt(this.value(), '@objects.ClientFilterField.UserLimitBelow');
                }
                function ExpiryDateAfterChanged() {
                    UpdateDate(kendo.toString(this.value(), "dd/MM/yyyy"), '@objects.ClientFilterField.ExpiryDateAfter');
                }
                function ExpiryDateBeforeChanged() {
                    UpdateDate(kendo.toString(this.value(), "dd/MM/yyyy"), '@objects.ClientFilterField.ExpiryDateBefore');
                }
                function txtClientNameChange() {
                    UpdateText(this.value, '@objects.ClientFilterField.ClientName');
                }

                function UpdateDropdownListSelection(newvalue, field) {
                   $.ajax({
                        type: 'POST',
                        url: "@Url.Action("UpdateClientFilterDropdownList", "Clients")",
                       data: { NewValue: newvalue, Field: field },
                       success: function (data) {
                           window.location.reload(true);
                       },
                       error: function (xhr, status, errorThrown) {
                            ToastrPopup(xhr.responseText, 'error');
                            console.log("xhr: " + xhr.responseText + " status: " + status + " errorThrown: " + errorThrown);
                        }
                    });
                }
                function UpdateDate(newvalue, field) {
                   $.ajax({
                        type: 'POST',
                        url: "@Url.Action("UpdateClientFilterDate", "Clients")",
                       data: { NewValue: newvalue, Field: field },
                       success: function (data) {
                           window.location.reload(true);
                       },
                       error: function (xhr, status, errorThrown) {
                            ToastrPopup(xhr.responseText, 'error');
                            console.log("xhr: " + xhr.responseText + " status: " + status + " errorThrown: " + errorThrown);
                        }
                    });
                }
                function UpdateText(newvalue, field) {
                   $.ajax({
                        type: 'POST',
                        url: "@Url.Action("UpdateClientFilterText", "Clients")",
                       data: { NewValue: newvalue, Field: field },
                       success: function (data) {
                           window.location.reload(true);
                       },
                       error: function (xhr, status, errorThrown) {
                            ToastrPopup(xhr.responseText, 'error');
                            console.log("xhr: " + xhr.responseText + " status: " + status + " errorThrown: " + errorThrown);
                        }
                    });
                }
                function UpdateInt(newvalue, field) {
                   $.ajax({
                        type: 'POST',
                        url: "@Url.Action("UpdateClientFilterInt", "Clients")",
                       data: { NewValue: newvalue, Field: field },
                       success: function (data) {
                           window.location.reload(true);
                       },
                       error: function (xhr, status, errorThrown) {
                            ToastrPopup(xhr.responseText, 'error');
                            console.log("xhr: " + xhr.responseText + " status: " + status + " errorThrown: " + errorThrown);
                        }
                    });
                }
            </script>
        </div>
    </body>
</html>
}

Website/RMSS Website/Views/Clients/ClientGrid.cshtml
@{
    ViewBag.Title = "Client Grid";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using RMSS_Website.Models.Clients;

@model IEnumerable<RMSS_Website.Models.Clients.ClientModelGrid>

@section content_Content {
    <!DOCTYPE html>


    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title></title>
    </head>
    <body>
        <div>
            <a href="~/Clients/ClientFilter" class="HyperlinkOnWhiteBackground">Return to Client Filter</a> <br /> <br /> <br />
            @(Html.Kendo().Grid(Model)
                                .Name("ClientGrid")
                                .Columns(columns => {
                                    columns.Bound(c => c.ClientName);
                                    columns.Bound(c => c.ClientStatus);
                                    columns.Bound(c => c.ExpiryDate).ClientTemplate("#= kendo.toString(ExpiryDate, \"dd/MM/yyyy\")#");
                                    columns.Bound(c => c.Modules);
                                    columns.Bound(c => c.UserLimit);
                                    columns.Bound(c => c.Version).ClientTemplate(@"#=Version#.0.#=SubVersion#"
                                        );
                                }).Scrollable().Sortable(sortable => sortable.AllowUnsort(true).SortMode(GridSortMode.SingleColumn).ShowIndexes(true)).Pageable(pageable => pageable.Refresh(true).PageSizes(true).ButtonCount(5)).DataSource(
                                    dataSource => dataSource.Ajax().Read(read => read.Action("GetClientGridData", "Clients")).PageSize(20)))
        </div>
    </body>
</html>
    }

Website/RMSS Website/Views/Clients/ClientInfo.cshtml
@{
    ViewBag.Title = "Client Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using RMSS_Website.Models.Clients
@using RMSS_Website.Objects.Web_Objects.CustomControl
@model RMSS_Website.Models.Clients.ClientModel

@section content_Content {
    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Client Info</title>
    </head>
    <body>
        <a href="~/Clients/SelectClient" class="HyperlinkOnWhiteBackground">Return to Client Selection</a> <br /> <br />
        <div style="float:left; width:60%;" id="divClientInfo">
            @SectionHeading.RenderMVC(Model.ClientName + " (" + Model.Status.SelectedStatusName + ")")
            <img id="imgClientLogo" src="@Url.Action("GetClientLogo", "Clients", new { ClientID = Model.ClientID })" height="150" style="max-width:100%;"/>
            <br />
            <table>
                <tr>
                    <td style="width:25%">Expiry Date: </td>
                    <td style="width:75%">@Model.ExpiryDate </td>
                </tr>
                <tr>
                    <td>User Limit: </td>
                    <td>@Model.UserLimit </td>
                </tr>
                <tr>
                    <td>Modules: </td>
                    <td>
                        <span>@Model.Modules.SelectedModuleNames</span>
                    </td>
                </tr>
                <tr>
                    <td>Production URL: </td>
                    <td><a href="@Model.ProductionURL" class="HyperlinkOnWhiteBackground" target="_blank">@Model.ProductionURL</a> </td>
                </tr>
                @if (!string.IsNullOrEmpty(Model.TrainingURL)) {
                    <tr>
                        <td>Training URL: </td>
                        <td><a href="@Model.TrainingURL" class="HyperlinkOnWhiteBackground" target="_blank">@Model.TrainingURL</a></td>
                    </tr>
                }
                @if (!string.IsNullOrEmpty(Model.ThirdURL)) {
                    <tr>
                        <td>Third URL: </td>
                        <td><a href="@Model.ThirdURL" class="HyperlinkOnWhiteBackground" target="_blank">@Model.ThirdURL</a></td>
                    </tr>
                }
                <tr>
                    <td style="vertical-align:top;">Contacts: </td>
                    <td>
                        @foreach (ClientContact contact in Model.Contacts) {
                            <span>@contact.Name (Office: @contact.OfficeNumber Mobile: @contact.MobileNumber Email: 
                                </span><a href="mailto:@contact.Email" class="HyperlinkOnWhiteBackground">@contact.Email</a><span>)</span> <br />
                        }
                    </td>
                </tr>
                <tr>
                    <td>Account Manager:  </td>
                    <td> @Model.LinkedEmployees.AccountManagerName </td>
                </tr>
                <tr>
                    <td>Client Support Coordinator: </td>
                    <td> @Model.LinkedEmployees.ClientSupportCoordinatorName </td>
                </tr>
                <tr>
                    <td>Created By: </td>
                    <td> @Model.CreatorPerson on @Model.CreateDate </td>
                </tr>
            </table>
        </div>
        <div style="float:right; width:35%;">
            @SectionHeading.RenderMVC("Notes")
            <table style="width:100%;">
                @{
                    var altRow = false;
                    foreach (ClientNote note in Model.Notes) {
                        <tr>
                            <td style="background-color:@(altRow ? "lightgrey" : "#E0EBEB");">
                                <div id="noteHeader">
                                    <span style="float:left;">@note.Heading</span>
                                    @if (note.Pinned != null && note.Pinned == true) {
                                        <img src="~/Images/pinpoint.gif" style="float:right;" />
                                    }
                                    <span style="float:right;">[@note.Creator - @note.CreateDate]</span>
                                </div>
                                <br />
                                <br />
                                <span>@note.Note</span>
                                <br />
                                <br />
                            </td>
                        </tr>
                        altRow = !altRow;
                    }
                }
            </table>
        </div>
        <style>
            .SectionHeading {
                border-bottom: 1px solid black;
            }
        </style>
    </body>
</html>

}

Website/RMSS Website/Views/Clients/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>